version: '2'
services:
    api:
        extends:
            file: docker-compose.yml
            service: api
        ports:
            - "8000:8000"
        volumes:
            - ./api:/usr/src/app
        environment:
            - APP_DEBUG
            # set APP_DEBUG env var to true on localmachine
    webapp:
        extends:
            file: docker-compose.yml
            service: webapp
        command: sh -c "yarn install && yarn dev"
            # on windows, add `--no-bin-links` after `yarn install`
            # DO NOT COMMIT THIS CHANGE
        ports:
            - "3000:3000"
        volumes:
            - ./webapp:/usr/src/app
