version: '2'
services:
    api:
        extends:
            file: docker-compose.yml
            service: api
        ports:
            - "8000:8000"
        volumes:
            - ./webapp:/usr/src/app
    webapp:
        extends:
            file: docker-compose.yml
            service: webapp
        command: sh -c "yarn install && yarn dev"
        ports:
            - "3000:3000"
        volumes:
            - ./webapp:/usr/src/app
