#   This configuration is the full-scale deployment config. Create
#   custom configurations to extend this for devleopment.

version: '2'
services:

    #
    #   Data stores
    #

    # [PostgreSQL] Database for Django API
    postgres:
        image: "postgres"
        ports:
            - "127.0.0.1:5432:5432"
        env_file: ".env"
        volumes:
            - /data/postgres:/var/lib/postgresql/data
        restart: always

    # [MongoDB] Datastore for microservies
    mongodb:
        image: "mongo"
        ports:
            - "127.0.0.1:27017:27017"
        volumes:
            - /data/mongodb:/data/db

    #
    #   Core apps
    #

    # [Django] Backend API (also has Nginx)
    api:
        image: "hackfsu/api"
        build: "./api"
        env_file: ".env"
        ports:
            - "127.0.0.1:8080:8080"
        restart: always
        volumes:
            - /data/media:/usr/src/app/media
        depends_on:
            - qr
            - push
            - postgres

    # [Express] Webapp
    webapp:
        image: "hackfsu/webapp"
        env_file: ".env"
        build: "./webapp"
        ports:
            - "127.0.0.1:3000:3000"
        restart: always


    #
    #   Microservices
    #

    # [Express] QR Service
    # This service name is depended upon by the .env
    # file and the API's nginx.conf
    qr:
        image: "hackfsu/qr-service"
        build: "services/profile"
        env_file: ".env"
        ports:
            - 127.0.0.1:8101:3000
        depends_on:
            - mongodb

    # [gorush] FCM/APN Push Server
    # This service actually sends the notifications.
    gorush:
        image: "appleboy/gorush"
        ports:
            - 127.0.0.1:8102:8088
        volumes:
            - ./services/gorush/config.yml:/config.yml
            - ./services/gorush/${IOS_CERT}:/certs.p12

    # [Express] Device ID Push Server
    # This service tracks uploaded device IDs and their platform.
    # When pushing notifactions, the notification is routed through
    # this server.
    push:
        image: "hackfsu/push-service"
        build: "services/push"
        env_file: ".env"
        ports:
            - 127.0.0.1:8103:3000
        depends_on:
            - mongodb
            - gorush
