# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 05:02
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('GEN', 'Gender'), ('ETH', 'Ethnicity')], max_length=3)),
                ('value', models.CharField(choices=[('Gender', (('MAL', 'Male'), ('FEM', 'Female'), ('OTH', 'Other'))), ('Ethnicity', (('ASI', 'Asian'), ('BLK', 'Black'), ('HIS', 'Hispanic'), ('MLT', 'Multicultural'), ('WHT', 'White'), ('OTH', 'Other')))], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HackerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first_hackathon', models.BooleanField()),
                ('is_adult', models.BooleanField()),
                ('agreed_to_mlh_data_sharing', models.BooleanField()),
                ('school_name', models.CharField(max_length=100)),
                ('school_year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=2)),
                ('school_major', models.CharField(max_length=100)),
                ('rsvp', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('attendee_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JudgeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, default='', max_length=1000)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, default='', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('H', 'High School'), ('C', 'College')], default='C', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('shirt_size', models.CharField(choices=[('m-s', "Men's Small"), ('m-m', "Men's Medium"), ('m-l', "Men's Large"), ('m-xl', "Men's XL"), ('m-2xl', "Men's XXL"), ('m-3xl', "Men's XXXL"), ('w-s', "Women's Small"), ('w-m', "Women's Medium"), ('w-l', "Women's Large"), ('w-xl', "Women's XL")], max_length=3)),
                ('waiver_signature', models.CharField(max_length=100)),
                ('diet', models.CharField(blank=True, default='', max_length=500)),
                ('github', models.CharField(blank=True, default='', max_length=100)),
                ('last_hackathon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Hackathon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WifiCred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('assigned_user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='helprequest',
            name='assigned_mentor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.MentorInfo'),
        ),
        migrations.AddField(
            model_name='anonstat',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon'),
        ),
    ]
