# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hackathon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
