# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170127_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeestatus',
            name='checked_in_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendeestatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendeestatus',
            name='rsvp_confirmed_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendeestatus',
            name='rsvp_email_sent_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hackerinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgeinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizerinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackerinfo',
            name='school_year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('SS', 'Super Senior'), ('GS', 'Graduate Student'), ('HS', 'High School Student'), ('RG', 'Recent College Graduate')], max_length=2),
        ),
    ]
