# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170127_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathoncountdown',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hackathonmap',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
