# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_scheduleitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='hackathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wificred',
            name='hackathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='assigned_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.MentorInfo'),
        ),
    ]
