# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170129_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorinfo',
            name='availability',
        ),
    ]
