# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_mentorinfo_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonsponsor',
            name='on_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
