# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20170211_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='description',
            new_name='request',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='location',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='attendee_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='location_floor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basement'), (2, 'Entrance Floor'), (3, 'Upper Floor')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='location_x',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='location_y',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
