# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_hackathonprize'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='attendee_phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
