# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20170219_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgingcriteria',
            name='devpost_name',
        ),
    ]
