# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_judgingcriteria_devpost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgingassignment',
            name='judge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.JudgeInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hack',
            name='extra_judging_criteria',
            field=models.ManyToManyField(blank=True, to='api.JudgingCriteria'),
        ),
        migrations.AlterField(
            model_name='judgingcriteria',
            name='criteria_type',
            field=models.SmallIntegerField(choices=[(0, 'Overall'), (1, 'Superlative'), (2, 'Manual')]),
        ),
    ]
