version: '2'
services:

    api:
        extends:
            file: ./.docker/base.yml
            service: api
        ports:
            - "8080:8000"

    webapp:
        extends:
            file: ./.docker/base.yml
            service: webapp

    db:
        extends:
            file: ./.docker/base.yml
            service: db
        environment:
            POSTGRES_USER: "hackfsu"
            POSTGRES_PASSWORD: "SEE_SECRETS_JSON"
        volumes:
            - /data/postgres:/var/lib/postgresql/data
