# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='name',
            field=models.CharField(default="HackFSU '17", max_length=100),
            preserve_default=False,
        ),
    ]
