# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170121_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerinfo',
            name='interests',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='hackerinfo',
            name='school_year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('SS', 'Super Senior'), ('GS', 'Graduate Student'), ('HS', 'High School Student')], max_length=2),
        ),
    ]
