# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170122_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='shirt_size',
            field=models.CharField(choices=[('m-s', "Men's Small"), ('m-m', "Men's Medium"), ('m-l', "Men's Large"), ('m-xl', "Men's XL"), ('m-2xl', "Men's XXL"), ('m-3xl', "Men's XXXL"), ('w-s', "Women's Small"), ('w-m', "Women's Medium"), ('w-l', "Women's Large"), ('w-xl', "Women's XL")], max_length=10),
        ),
    ]
