# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170128_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonsponsor',
            name='tier',
            field=models.SmallIntegerField(choices=[(0, 'Co-Host'), (1, 'Tier 3'), (2, 'Tier 2'), (3, 'Tier 1'), (4, 'Partner')], default=0),
        ),
    ]
