# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170128_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Key'), (1, 'Tech Talk'), (2, 'Food'), (3, 'Social'), (4, 'Miscellaneous')], default=0),
        ),
    ]
