# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_helprequest_attendee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JudgingAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Complete'), (2, 'Canceled')], default=0)),
                ('hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hack')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='JudgingCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('point_contribution', models.IntegerField()),
                ('criteria_type', models.SmallIntegerField(choices=[((0,), 'Overall'), (1, 'Superlative'), (2, 'Manual')])),
                ('description_long', models.CharField(max_length=500)),
                ('description_short', models.CharField(max_length=100)),
                ('devpost_name', models.CharField(max_length=200)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='JudgingExpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('table_number_start', models.IntegerField()),
                ('table_number_end', models.IntegerField()),
                ('current', models.BooleanField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='JudgingGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('by_judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.JudgeInfo')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.JudgingCriteria')),
                ('hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hack')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon')),
            ],
        ),
        migrations.AddField(
            model_name='hack',
            name='extra_judging_criteria',
            field=models.ManyToManyField(to='api.JudgingCriteria'),
        ),
        migrations.AddField(
            model_name='hack',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon'),
        ),
    ]
