# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170219_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon')),
            ],
        ),
    ]
