# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_previewemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hack',
            name='current_judges',
            field=models.ManyToManyField(blank=True, related_name='judges_current', to='api.JudgeInfo'),
        ),
        migrations.AddField(
            model_name='hack',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='judges', to='api.JudgeInfo'),
        ),
        migrations.AddField(
            model_name='hack',
            name='times_judged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hack',
            name='total_judge_score',
            field=models.IntegerField(default=0),
        ),
    ]
