# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20171105_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hack')),
                ('superlative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.JudgingCriteria')),
            ],
        ),
    ]
