# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-25 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_nomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='hexcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
